README.rst
To satisfy one of the requirements that @stscicrawford posted on https://jira.stsci.edu/browse/JUSI-5 .
cc @jhunkeler
Related:
* spacetelescope/hstcal#403
* spacetelescope/calcos#52
=> DOC: Add JupyterHub to README

Dockerfile, caldp/create_previews.py, caldp/log.py, caldp/process.py, scripts/README.md, scripts/caldp-cal-env, scripts/caldp-create-previews, scripts/caldp-docker-run-container, scripts/caldp-docker-run-pipeline, scripts/caldp-get-output-path, scripts/caldp-image-build, scripts/caldp-image-config, scripts/caldp-image-push, scripts/caldp-install-fitscut, scripts/caldp-onsite-process, scripts/caldp-process, scripts/caldp-process-core, scripts/caldp-remote-process, scripts/caldp-s3-env, setup.py
Added caldp-process code and scripts used for AWS batch processing.
Added scripts to setup.py,  added Dockerfile.
=> Add CALCLOUD nano-pipeline code,  Dockerfle, wrapper scripts.

caldp/create_previews.py, caldp/log.py, caldp/process.py
Code cleanup attempting to address automated style checks.
=> Improve formatting

caldp/process.py, scripts/caldp-process-core
This adds the ability for a local filesystem output location to be specified by using a uri with the local: prefix.
=> WIP bare min functionality for local processing output locations

caldp/create_previews.py, caldp/process.py, scripts/caldp-process, scripts/caldp-process-core
Adds an input uri variable that allows a local directory to be used rather than downloading files via astroquery. The string should be either like `astroquery://` or `local:/path/to/dir`
=> Support for local input directories

README.rst
Adding in a short note about the purpose of the repository
=> Adding a note to the README

scripts/caldp-process
fixed an issue that caused local output directory structure for messages to diverge from AWS directory structure
=> local message directory structure fix

scripts/caldp-docker-run-container, scripts/caldp-process
to match calcloud.sync functionality
=> added paths to output files to the message 

README.rst
Testing Github changes with Lisa S.
=> added brief message describing where to pull docker images from

README.rst
Clarified a comment and be introduced to github workflow.  I decreased many double spaces to single spaces.
=> Clarify a comment.

caldp/process.py
Demo for Team violet as well as some minor logic changes in dealing with the S3 output path.
=> minor updates to caldp.process.get_output_path for s3 logic

.github/workflows/build.yml, caldp/create_previews.py, caldp/file_ops.py, caldp/messages.py, caldp/process.py, caldp/tests/test_all.py, scripts/caldp-process
- support for local tar inputs
- append process.txt to trailer
- add .trigger ext to proc message
- optional crds context pinning in assign_bestrefs (process.py)
- set crds context explicitly in Github Actions for testing
=> support for local tar input, message .trigger extension, append log to trailer file, crds_context pinning

caldp/process.py, caldp/tests/test_all.py
* add proper key=value pairs from the env file to the environment before processing
* adds test coverage via another ipppssoot
=> handle ipppssoot_cal_env.txt file

.github/workflows/checks.yml, caldp/file_ops.py, caldp/messages.py, caldp/process.py, caldp/tests/test_all.py
and that tests are passing.
Does NOT test that cleanup is doing a good job yet; simply tests that the cleanup codes are not erroring.
edit: leaving further testing of how "well" it's cleaning up for a different PR.
=> uncommented all clean_up code and ensured test coverage 

caldp/file_ops.py, caldp/messages.py, caldp/tests/test_all.py
due to cleanup happening too soon
=> fixing processed-ipppssoot.trigger message not appearing 

scripts/caldp-config-aws, scripts/caldp-image-config
goes with calcloud pr https://github.com/spacetelescope/calcloud/pull/75
=> base image update and s3 aws config

caldp/process.py, scripts/caldp-process
companion to https://github.com/spacetelescope/calcloud/pull/80
will squash merge
=> Pull CRDS Context from primary S3 processing bucket

caldp/exit_codes.py
Modified exit_codes module so that all exit code values have some explanation and ValueError is not raised.
=> No exit_code ValueError,  always explained

caldp/sysexit.py, setup.cfg
Didn't run this on Batch but I think the doctests either didn't change or illustrate what this does.
=> Updates to handle untrapped exceptions formerly mapped to '1' but w/o traceback.

.github/workflows/build.yml, caldp/file_ops.py, caldp/tests/test_all.py, scripts/caldp-config-aws, scripts/caldp-image-config
Putting PR in place to update the base image and the default CRDS context, once we are ready to move on to that in Test
=> WIP: base image update

.github/workflows/build.yml, caldp/tests/test_all.py, scripts/caldp-image-config
* updates default base image to CALDP_20210505_CAL_final
* updates default CRDS CONTEXT to 0910 (ops)
=> base image and default crds context updates

.github/workflows/build.yml, caldp/tests/test_all.py
* update default crds context to 0922
=> default crds version updates

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/docker.yml
Adds push buttons for check, build, docker workflows
Updates Ubuntu from 18.04 to 20.04
=> Add GitHub pushbuttons

caldp/process.py
Created check_tar_members function to filter extracted tarfilemembers in a way bandit thinks is safe.
=> Placate bandit for tarfile extraction
