caldp/__init__.py
caldp/_astropy_init.py
caldp/conftest.py
caldp/create_previews.py
caldp/log.py
caldp/process.py
pyproject.toml
scripts/caldp-image-config
tox.ini

updated pyproject with a black config to allow line lengths of 120. Same for tox.ini so flake8 will allow it. Ran black on all python scripts to reformat and standardize their syntax.

formatting updates to python scripts for flake8 

---

scripts/caldp-image-config
scripts/caldp-process-aws

Finished caldp-process-aws script,  keeping old interface of caldp-pocess for use by the AWS Batch job definition.
Switched default CALDP_IMAGE_REPO back to AWS ECR for the DMD-TEST prototype.

Finish caldp-process-aws wrapper function

---

README.rst
scripts/caldp-docker-run-container

Added env var CALDP_DOCKER_RUN_PARS to support setting the Docker switches which precede the image name.  This enables turning off both -it and  -p 8888:8888 which were causing problems in the onsite HST HTCondor pipeline;  they are now off by default,  debugging or supporting JupyterHub requires defining this to turn them on as needed.   The only remaining switch on by default is --rm which does automatic Docker container cleanup which should be the non-debug norm.
-it was causing problems with processes due to no TTY. 
-p 8888:8888 was causing problems with multiple processes all wanting port 8888.

Add env var to customize Docker switches

---

caldp/process.py
caldp/tests/test_all.py

Fixes missing version keywords for STIS _raw and _wav files.
Updated file sizes for COS test la8q99030

Add missing version keywords for STIS

---

Dockerfile
ascii_fix.patch

patches the photutils __init__.py in the container to read the CITATIONS.rst file as utf8

photutils import fix for the CALDP_20201208_DRZ_final base image

---

ascii_fix.patch
scripts/caldp-image-config

added separate tags for the docker base image and the image that will be created by the user running caldp-image-build

Separate tag for docker base image in caldp-image-config

---

.github/workflows/build.yml
.github/workflows/docker.yml

the purpose of these tests is to test our wrappers around the calibration code; however, by using "latest", we inadvertently test the latest calibration code against the operational CRDS context, which will periodically fail for reasons outside our control.
We can't get rid of "stable" at the moment because in astroconda, the caldp envs have different names than they do on dockerhub, unless the names are "stable" or "latest". So, the safest and easiest thing to do at the moment is only test against stable.

removed latest base image from testing matrix

---

caldp/process.py
caldp/tests/test_all.py

process.py was not set up to run runastrodriz for ACS and WFC3 singletons, but it should be run so e.g., _drz files are generated for singletons as well.

Add runastrodrizzle for ACS and WFC3 singletons

---

caldp/process.py

caldp receives environment variables used to set three HST keywords in the raw files, which are transferred to the calibrated products during calibration.

new HST keywords for cloud software versions

---

.gitignore
caldp/create_previews.py
caldp/exit_codes.py
caldp/file_ops.py
caldp/log.py
caldp/messages.py
caldp/process.py
caldp/sysexit.py
caldp/tests/test_all.py
scripts/caldp-docker-run-container
scripts/caldp-ecr-login
scripts/caldp-image-build
scripts/caldp-image-sh
scripts/caldp-process
tox.ini

Still working on it,  but so far:
Improvements to error reporting in caldp.process and caldp-process to better
utilize program exit status, most critically to characterize Astrodrizzle
memory errors with exit status visible in the batch failure events.
Added exit_codes.py file to be shared-with/copied-to CALCLOUD verbatim.
Added exit handling functions and context managers,  with doctests,  to make
exit handling code standard and succinct.  sysexit module.
Added caldp-ecr-login <admin_role> script to make it simpler to login to
the ECR repository.  Personal perk.
Added tox.ini to facilitate command line flake8, black, and bandit tests.
Added exit error simulation via CALDP_SIMULATE_ERROR env var which
can be defined to values in exit_codes.py to simulate exceptions/exits.
Added default …

Exit status improvements

---

Dockerfile

Modified Dockerfile to do yum updates and remove kernel-devel package as a direct way to address 11/12 "high" criticality ECR scan vulnerabilities as well as all lower level vulnerabilities.   The only remaining "high" was limited to ARM platforms.

CALCLOUD-235 Address ECR scan vulnerabilities.

---

caldp/process.py

there is a theory that our infinite job hangs are due to multiprocessing issues when python runs out of memory. This restricts astrodrizzle to a single CPU in the hopes of memory failures relinquishing their threads back to the OS and eventually, Batch.

runastrodriz restricted to single core

---

caldp/_astropy_init.py

This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497

MNT: Remove unused astropy config code

---

caldp/create_previews.py
caldp/file_ops.py
caldp/tests/test_all.py

If a job fails in caldp, there are no output files in the tarball for s3 (only previews). In the case of a failure, this tars and uploads the input files (+previews) instead which can be useful for debugging.

failed-jobs/tar-inputs-for-debugging

---

caldp/process.py
caldp/sysexit.py
caldp/tests/test_all.py

adds a decorator function to sysexit with a configurable exponential backoff retry. It is safe to use inside a sysexit.exit_on_exception context manager, as it will catch the exception during retrying, and then eventually re-raise it at the end to be caught by the context manager.

crds bestrefs retries

---

Dockerfile
caldp/exit_codes.py
caldp/process.py
caldp/sysexit.py
scripts/caldp-process

Added explanation of negative subprocess return codes which correspond to UNIX
signals which kill processes.  Reporting the signal status associated with a
killed process is roughly equivalent to getting the status reported in the
aftermath of a core dump.
Re-order Dockerfile and use developer user for pip installs to avoid pip complaints
and improve typical build times.
Add "ulimit -a" dump to caldp-process to get the container's perception of various
process limits,  including core dump configuration;  this may be fictional and/or
require additional configuration in Terraform to set the docker run --ulimit
parameter.

Explain subprocess signal exit codes

---

.github/scripts/merge-main-to-develop.sh
.github/scripts/tag-latest.sh
.github/scripts/tag-stable.sh
.github/workflows/merge-main-to-develop.yml
.github/workflows/tag-latest.yml
.github/workflows/tag-stable.yml

* adds a GA to tag stable on any push to main
* adds GA to merge main back into develop on any push to main
* adds GA to tag latest on any push to dev
- note: this doesn't work if the push was done in another GA, hence the merge GA has an extra step to run this script as well
The intended workflow for developers here is that any push to main came either from a hotfix, or a release candidate branch. Any changes there need merged back to develop and this should remove the chance of that getting overlooked during a release. I do have some concerns about that merge failing, and how exactly to handle that.
This is all in the context of me needing to write procedures for other people to be able to create releases. So there will be instructions somewhere on exactly what the procedure is. This …

actions to tag on push and merge main to develop

---

.github/scripts/check-merge-main2develop.sh
.github/workflows/PR-check-merge.yml

* adds workflow to check for merge conflicts with develop, when a PR is opened against main
* this is intended for informational purposes only, because after the PR is merged, another workflow will attempt to auto-merge main back into develop. If this check fails, then that will fail too. At that point developer intervention is required to fix the merge conflicts from main back to develop.
* note that you do not need to fix the conflicts before merging to main. _**informational purposes only**_

PR merge conflict check workflow

---

.github/workflows/build.yml

You are using a deprecated version of `codecov-action`, see https://github.com/codecov/codecov-action for more details. xref astropy/astropy#12245
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

MNT: Update codecov-action version to v2

---

.dockerignore
.gitignore
caldp-setup
caldp/file_ops.py
caldp/messages.py
caldp/process.py
caldp/tests/test_all.py
scripts/caldp-image-build
scripts/caldp-test
setup.cfg

**Initial PR with two major remaining problems:**
1. All S3 output tests fail identically.
2. Logging is not working well with pytest.
**Changes:**
Added moto to caldp requirements.txt
Added moto and bucket creation to test_all.py
Wrapped test_all.coretst() with moto_s3,  core multi-mode parameterized processing test 
Working s3:// input tarball?  passing input tests
Working S3 output tarball? all 3 input cases failing for S3 outputs due to auxiliary files
Added coverage testing to caldp-test,  outputting to  htmlcov directory,  see index.html.
Fixed moto incompatibility with test_all.list_objects by switching to boto vs subprocess.   
Simplified/fixed file_ops.cleanup.
Added test.log file to caldp-test.
Defined defaults for CALDP test bucket names.
Added additional doctest coverage to …

Initial moto testing for S3 inputs

---

caldp-setup
caldp/create_previews.py
caldp/log.py
caldp/messages.py
caldp/process.py
caldp/sysexit.py
caldp/tests/test_all.py
changelog.md
scripts/caldp-process
scripts/caldp-test

- enabled S3 output tests and made related adjustments
- overhauled logging, dropping Python logging for print(),  to:
reduce complexity
obtain log output running under pytest
avoid writing to same log file from two processes
concurrently:  the .py's and caldp-process
re-enable console output of caldp .py logs

Enable S3 output tests,  improve logging

---

caldp/process.py

Add p.wait() to ensure exit code is propagated

Add p.wait() to ensure exit code is propagated
